name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Sala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.11
    - name: Run tests
      run: sbt test
